#ifndef _MX_RENDER_ESTANDSHADER_H_
#define _MX_RENDER_ESTANDSHADER_H_

namespace mx
{
	namespace render
	{
		enum E_STAND_SHADER {
			ESS_SHADER_IDENTITY = 0, 
			ESS_SHADER_FLAT, 
			ESS_SHADER_SHADED, 
			ESS_SHADER_DEFAULT_LIGHT, 
			ESS_SHADER_POINT_LIGHT_DIFF,
			ESS_SHADER_TEXTURE_REPLACE, 
			ESS_SHADER_TEXTURE_MODULATE, 
			ESS_SHADER_TEXTURE_POINT_LIGHT_DIFF, 
			ESS_SHADER_TEXTURE_RECT_REPLACE,
			ESS_SHADER_LAST
		};
	}
}

#endif